using Solanist.Infrastructure.Persistence.Documents;

namespace Solanist.Infrastructure.Persistence;

internal static class FutureStaffJobsSeed
{
    public static IReadOnlyList<StaffJobDocument> Jobs(DateOnly today) =>
    [
        OpenJob(
            "job-005",
            "staff-001",
            today.AddDays(3),
            1,
            "booking-future-001",
            "prop-001",
            "cust-001",
            "Nicolette Botha",
            "082 123 4567",
            "nicolette.botha@email.com",
            "Hurlingham View",
            "Sandton",
            "2196",
            12,
            5.2,
            "Quarterly Solar Care",
            "09:00 AM – 11:00 AM"),
        OpenJob(
            "job-006",
            "staff-001",
            today.AddDays(7),
            1,
            "booking-future-002",
            "prop-linda-001",
            "cust-003",
            "Linda Pretorius",
            "082 456 7890",
            "linda.pretorius@email.com",
            "Parkhurst Villa",
            "Parkhurst",
            "2193",
            10,
            4.2,
            "Bi-Annual Care",
            "08:00 AM – 10:00 AM"),
        OpenJob(
            "job-007",
            "staff-002",
            today.AddDays(5),
            1,
            "booking-future-003",
            "prop-david-001",
            "cust-002",
            "David Khumalo",
            "083 234 5678",
            "david.khumalo@email.com",
            "Sandton Ridge",
            "Sandton",
            "2196",
            16,
            6.9,
            "Quarterly Solar Care",
            "10:00 AM – 12:00 PM"),
    ];

    private static StaffJobDocument OpenJob(
        string id,
        string staffId,
        DateOnly date,
        int routeOrder,
        string bookingId,
        string propertyId,
        string customerId,
        string customerName,
        string phone,
        string email,
        string address,
        string city,
        string postcode,
        int panelCount,
        double systemSizeKw,
        string planType,
        string scheduledTime) => new()
    {
        Id = id,
        StaffId = staffId,
        BookingId = bookingId,
        PropertyId = propertyId,
        CustomerId = customerId,
        CustomerName = customerName,
        CustomerPhone = phone,
        CustomerEmail = email,
        Address = address,
        City = city,
        Postcode = postcode,
        ServiceType = "Solar Panel Cleaning",
        PlanType = planType,
        ScheduledTime = scheduledTime,
        ScheduledDate = date.ToString("yyyy-MM-dd"),
        Status = "scheduled",
        RouteOrder = routeOrder,
        PanelCount = panelCount,
        SystemSizeKw = systemSizeKw,
        RoofType = "Tile Roof",
        AccessShort = "Standard access",
        AccessNotes = "Standard property access.",
        HeroImageUrl = MongoSeedData.PropertyImageUrl,
        Instructions = "Standard clean — follow checklist.",
        Checklist = DefaultChecklist(),
        PhotoSlots = [],
        BeforePhotos = [],
        AfterPhotos = [],
    };

    private static List<StaffChecklistItemDocument> DefaultChecklist() => [
        new() { Id = "c1", Label = "Roof access confirmed", Completed = false, Required = true },
        new() { Id = "c2", Label = "Safety check completed", Completed = false, Required = true },
        new() { Id = "c3", Label = "Panels cleaned", Completed = false, Required = true },
    ];
}
